{"name": "test_002_ddt_login_using_invalid_credentials", "status": "passed", "attachments": [{"name": "Invalid Login credentials.png", "source": "088664fe-da91-488e-8e29-e4051cdf86a5-attachment.png", "type": "image/png"}, {"name": "Error Message.png", "source": "8d887271-335e-488c-8b15-d0924885d125-attachment.png", "type": "image/png"}, {"name": "Invalid Login credentials.png", "source": "b43ce63d-a0cd-4f27-a468-42c19f36564b-attachment.png", "type": "image/png"}, {"name": "Error Message.png", "source": "fc96542f-3d47-4d20-8f28-74caa68a9ec5-attachment.png", "type": "image/png"}, {"name": "log", "source": "529f518e-9b5f-4940-abde-6bdbfb9fab9d-attachment.txt", "type": "text/plain"}], "start": 1712744562246, "stop": 1712744569270, "uuid": "f2982bde-5584-4521-9016-72f4d4603d39", "historyId": "2d5f26479c72f7b94300f5bcec10ac60", "testCaseId": "2d5f26479c72f7b94300f5bcec10ac60", "fullName": "testCases.test_login.Test_001_Login#test_002_ddt_login_using_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_001_Login"}, {"name": "host", "value": "DESKTOP-DNPAJHF"}, {"name": "thread", "value": "3892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}]}