{"name": "test_002_ddt_login_using_invalid_credentials", "status": "passed", "attachments": [{"name": "Invalid Login credentials.png", "source": "8298615e-b979-486a-a53a-cbfe4c601c1b-attachment.png", "type": "image/png"}, {"name": "Error Message.png", "source": "0aa72bce-a0b6-4205-ba4f-267f72b9780f-attachment.png", "type": "image/png"}, {"name": "Invalid Login credentials.png", "source": "209c1e38-6941-46a9-8a00-ad6a9ddd658b-attachment.png", "type": "image/png"}, {"name": "Error Message.png", "source": "2e2c7734-f1bc-4277-a3bc-9efced487f9b-attachment.png", "type": "image/png"}, {"name": "log", "source": "e29b02b0-7040-4d4d-a516-2a2041e4e66b-attachment.txt", "type": "text/plain"}], "start": 1712744601379, "stop": 1712744609152, "uuid": "7acc76c6-e3a2-4639-bd80-f1a714119387", "historyId": "2b31a9bf6e9ba6ed3482d050c7c8c8e0", "testCaseId": "2b31a9bf6e9ba6ed3482d050c7c8c8e0", "fullName": "testCases.test_ddt_login.Test_002_DDT_Login#test_002_ddt_login_using_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_ddt_login"}, {"name": "subSuite", "value": "Test_002_DDT_Login"}, {"name": "host", "value": "DESKTOP-DNPAJHF"}, {"name": "thread", "value": "9380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_ddt_login"}]}